### ISSUE TITLE
【要望】段階付けした画像サイズ パラメーターの追加

### ISSUE THREAD

**Issue by xakuro** [katsushi-kawamori/Simple-Blog-Card-Templates#5]
現在の画像サイズは0から200の数値ですが、テンプレートによってはこの画像サイズに合わせるのが難しい場合があります。
画像サイズを数段階程度（大、中、小など）でグレーディングしたパラメーターがあれば嬉しいです。

**Comment by katsushi-kawamori** [comment]
要望ありがとうございます。ですが、ちょっと意味がわかりません。数字では無く、ラジオボタンで大中小から選ぶと言う事でしょうか？その際の数値はどうなるのでしょう？

**Comment by xakuro** [comment]
大中小の選択項目と数値項目の両方があってもいいのかなと思うのですがどうでしょうか？

**Comment by katsushi-kawamori** [comment]
大中小は、例えば、WordPressのメディアの設定のサムネイルサイズ、中サイズ、大サイズに合わせるとか？
設定にすると複雑になるので、設定は今まで通りで、フィルターだして、イジりたい人だけイジるという形の方が私にとっては楽ですね。

**Comment by xakuro** [comment]
いろいろ考えると難しいですね。
とりあえず私の実装したいことは、現在の画像サイズでもできる（100未満は小、以上は大とか）ので、この issue は一旦閉じます。
